---
version: '3.7'
services:

  bt-postgre:
    container_name: bt-postgre
    image: postgres:14
    networks:
      - bt-backend
    volumes:
      - ./docker-volumes/bm-postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped
  
  bt-backend:
    container_name: bt-backend
    networks:
      - bt-backend
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: backend
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    environment:
      - DB_HOST=bt-postgre
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  bt-frontend:
    container_name: bt-frontend
    build: 
      context: .
      dockerfile: docker/Dockerfile
      target: frontend
    ports: 
      - 8043:8043

networks:
  bt-backend: {}